### PR TITLE
fix: documentation and review..

### LINKED ISSUE #1: Documentation Review
__Expected Behavior:__

* It's the chart that should be the first visible component, not a giraffe table
* More documentation and explanation for the end user (developers) is needed.

__Current Behavior:__

__Possible Solution:__

__Steps/Code to Reproduce the Problem:__

1. step1
1. ...

__Specifications:__

- Version:
- Platform:

### PR DESCRIPTION
**Pull request by ivankudibal**
Fixes #1 

## Proposed Changes

_Briefly describe your proposed changes:_

* Make the table show up as the last component because it's the least important and hides the preset and chart.
* Review the Best practice tab, fix style and English grammar
* Review and add the text to Homepage, oriented for first-time visitors and end-users. Keep the original text in the Design section. Add H3.
* Add intro to README as well as the procedure for beginners.
  
## Checklist

- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] Tests run successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/pages/BestPracticePage.tsx [hunk 1]
```diff
@@ -39,8 +15,67 @@ export const BestPracticePage: React.FC<TBestPracticePageProps> = (props) => {
...
+            <div>
+              <ul>
+                <li>server</li>
+                  <ul>
+                    <li>low-end internet connection</li>
+                    <li>less data on user browser</li>
+                  </ul>
+                  <li>client</li>
+                  <ul>
+                    <li>all server side benefits mentioned above</li>
```
Comment (Sciator) [inline ui/src/pages/BestPracticePage.tsx]: Not true - all data sent to user browser so it's opposite of server benefits

File: ui/src/pages/HomePage.tsx [hunk 2]
```diff
@@ -4,16 +4,83 @@ import React from "react";
...
-      <strong>normalizedDataFromTable</strong> show proposed function for easier more "JavaScript-ish" working with incoming influx data. There should be only simple transformation needed after data normalization function.
-      <div />
-      Simplification algorithm presented on Best practice tab is <strong>not</strong> used for libraries (original data is used)
+    <Card title="Visualize InfluxDB query results by using the 3rd party React components">
+
+      <div>
+
+        <p>This project is a <strong>playground for React front
+        developers</strong> that look for ways to visualize
+        <strong>InfluxDB</strong> query results by using the 3rd party
```
Comment (Sciator) [inline ui/src/pages/HomePage.tsx]: Some strong text has no space around ("visualizeInfluxDB" instead of "visualize InfluxDB")

**Review by Sciator — APPROVED** [review]
